# permissions for end users to view appwrappers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appwrapper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mcad
    app.kubernetes.io/part-of: mcad
    app.kubernetes.io/managed-by: kustomize
  name: appwrapper-viewer-role
rules:
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - appwrappers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - appwrappers/status
  verbs:
  - get
