# permissions for end users to edit appwrappers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appwrapper-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mcad
    app.kubernetes.io/part-of: mcad
    app.kubernetes.io/managed-by: kustomize
  name: appwrapper-editor-role
rules:
- apiGroups:
  - mcad.my.domain
  resources:
  - appwrappers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcad.my.domain
  resources:
  - appwrappers/status
  verbs:
  - get
