# permissions for end users to edit clusterinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterinfo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mcad
    app.kubernetes.io/part-of: mcad
    app.kubernetes.io/managed-by: kustomize
  name: clusterinfo-editor-role
rules:
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - clusterinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - clusterinfoes/status
  verbs:
  - get
