---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mcad.my.domain
  resources:
  - appwrappers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcad.my.domain
  resources:
  - appwrappers/finalizers
  verbs:
  - update
- apiGroups:
  - mcad.my.domain
  resources:
  - appwrappers/status
  verbs:
  - get
  - patch
  - update
