---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - clusterinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - clusterinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - mcad.codeflare.dev
  resources:
  - clusterinfoes/status
  verbs:
  - get
  - patch
  - update
